application: happy-birthday-481
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css

- url: /javascript
  static_dir: javascript
  
- url: /images
  static_dir: images

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"
